In [1]:
import numpy as np
import pandas as pd
import tensorflow

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('Data\covid_toy.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\singh\AppData\Local\Temp\ipykernel_23656\3253462189.py:1: SyntaxWarning: invalid escape sequence '\c'
  df = pd.read_csv('Data\covid_toy.csv')

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.models import Sequential

In [4]:
lb = LabelEncoder()

cat = [x for x in df.columns if df[x].dtype=='O']

for col in cat:
    df[col] = lb.fit_transform(df[col])

df.head()

   age  gender  fever  cough  city  has_covid
0   60       1  103.0      0     2          0
1   27       1  100.0      0     1          1
2   42       1  101.0      0     1          0
3   31       0   98.0      0     2          0
4   65       0  101.0      0     3          0

In [5]:
X = df.drop(columns=['has_covid'])
Y = df['has_covid']

In [6]:
scaler = StandardScaler()

In [7]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [8]:
model = Sequential([
    Dense(units=128, activation='relu', input_shape=(x_train_scaled.shape[1],)),
    Dropout(0.3),
    Dense(units=64, activation='relu'),
    Dense(units=1, activation='sigmoid')
])

c:\Users\singh\OneDrive\Desktop\ANN on Attrition\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [9]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 128)            │           768 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9,089 (35.50 KB)

 Trainable params: 9,089 (35.50 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
loss_fn = tensorflow.keras.losses.BinaryCrossentropy()
opt = tensorflow.keras.optimizers.Adam(learning_rate=0.1)

In [11]:
model.compile(optimizer=opt, loss=loss_fn, metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [15]:
## Training the Model
model.fit(
    x_train_scaled, y_train, validation_data=(x_test_scaled, y_test), epochs=50)

Epoch 1/50

3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 81ms/step - accuracy: 0.4500 - loss: 0.6946 - val_accuracy: 0.6500 - val_loss: 0.6829
Epoch 2/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6747
Epoch 3/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5250 - loss: 0.6924 - val_accuracy: 0.6500 - val_loss: 0.6699
Epoch 4/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5250 - loss: 0.6931 - val_accuracy: 0.6500 - val_loss: 0.6676
Epoch 5/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5250 - loss: 0.6938 - val_accuracy: 0.6500 - val_loss: 0.6667
Epoch 6/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5250 - loss: 0.6936 - val_accuracy: 0.6500 - val_loss: 0.6680
Epoch 7/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5250 - loss: 0.6929 - val_accuracy: 0.6500 - val_loss: 0.6696
Epoch 8/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5250 - loss: 0.6923 - val_accuracy: 0.6500 - val_loss: 0.6728
Epoch 9/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6764
Epoch 10/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5250 - loss: 0.6919 - val_accuracy: 0.6500 - val_loss: 0.6796
Epoch 11/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6830
Epoch 12/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5250 - loss: 0.6920 - val_accuracy: 0.6500 - val_loss: 0.6845
Epoch 13/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6850
Epoch 14/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6863
Epoch 15/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6877
Epoch 16/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5250 - loss: 0.6926 - val_accuracy: 0.6500 - val_loss: 0.6876
Epoch 17/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6884
Epoch 18/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6894
Epoch 19/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5250 - loss: 0.6927 - val_accuracy: 0.6500 - val_loss: 0.6891
Epoch 20/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5250 - loss: 0.6927 - val_accuracy: 0.6500 - val_loss: 0.6867
Epoch 21/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6850
Epoch 22/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6825
Epoch 23/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6814
Epoch 24/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6812
Epoch 25/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5250 - loss: 0.6928 - val_accuracy: 0.6500 - val_loss: 0.6796
Epoch 26/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5250 - loss: 0.6919 - val_accuracy: 0.6500 - val_loss: 0.6803
Epoch 27/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6814
Epoch 28/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.5250 - loss: 0.6919 - val_accuracy: 0.6500 - val_loss: 0.6825
Epoch 29/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6837
Epoch 30/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5250 - loss: 0.6924 - val_accuracy: 0.6500 - val_loss: 0.6834
Epoch 31/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5250 - loss: 0.6924 - val_accuracy: 0.6500 - val_loss: 0.6851
Epoch 32/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5250 - loss: 0.6924 - val_accuracy: 0.6500 - val_loss: 0.6856
Epoch 33/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5250 - loss: 0.6924 - val_accuracy: 0.6500 - val_loss: 0.6834
Epoch 34/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6814
Epoch 35/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6795
Epoch 36/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.5250 - loss: 0.6919 - val_accuracy: 0.6500 - val_loss: 0.6794
Epoch 37/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5250 - loss: 0.6919 - val_accuracy: 0.6500 - val_loss: 0.6789
Epoch 38/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6790
Epoch 39/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5250 - loss: 0.6918 - val_accuracy: 0.6500 - val_loss: 0.6774
Epoch 40/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5250 - loss: 0.6922 - val_accuracy: 0.6500 - val_loss: 0.6758
Epoch 41/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5250 - loss: 0.6920 - val_accuracy: 0.6500 - val_loss: 0.6756
Epoch 42/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5250 - loss: 0.6924 - val_accuracy: 0.6500 - val_loss: 0.6762
Epoch 43/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6750
Epoch 44/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6745
Epoch 45/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6751
Epoch 46/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5250 - loss: 0.6921 - val_accuracy: 0.6500 - val_loss: 0.6760
Epoch 47/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6773
Epoch 48/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5250 - loss: 0.6920 - val_accuracy: 0.6500 - val_loss: 0.6768
Epoch 49/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5250 - loss: 0.6925 - val_accuracy: 0.6500 - val_loss: 0.6777
Epoch 50/50
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5250 - loss: 0.6920 - val_accuracy: 0.6500 - val_loss: 0.6767

In [16]:
loss, accuracy = model.evaluate(x_test_scaled, y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6500 - loss: 0.6767

In [17]:
print(f"Test Loss : {loss:.4f} Test Accuracy = {accuracy:.4f}")

Test Loss : 0.6767 Test Accuracy = 0.6500