In [24]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [25]:
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [26]:
df = pd.read_csv('Data\Attrition - Attrition.csv')
df.head()

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\singh\AppData\Local\Temp\ipykernel_5708\3923022382.py:1: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv('Data\Attrition - Attrition.csv')

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [27]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [29]:
cat_cols = [x for x in df.columns if df[x].dtype == 'object']
cat_cols = ['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']
cat_cols

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [30]:
X = df.drop(columns=['Attrition'], axis=1)
Y = df['Attrition']

In [31]:
X_encoded = pd.get_dummies(X, columns= cat_cols, drop_first=True)
X_encoded = X_encoded.astype(int)
X_encoded.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0,0,0,0,0,1,0,0,1,1
1,49,279,8,1,1,2,3,61,2,2,...,0,0,0,0,1,0,0,1,0,0
2,37,1373,2,2,1,4,4,92,2,1,...,1,0,0,0,0,0,0,0,1,1
3,33,1392,3,4,1,5,4,56,3,1,...,0,0,0,0,1,0,0,1,0,1
4,27,591,2,1,1,7,1,40,3,1,...,1,0,0,0,0,0,0,1,0,0

In [32]:
X_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 47 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   DailyRate                          1470 non-null   int64
 2   DistanceFromHome                   1470 non-null   int64
 3   Education                          1470 non-null   int64
 4   EmployeeCount                      1470 non-null   int64
 5   EmployeeNumber                     1470 non-null   int64
 6   EnvironmentSatisfaction            1470 non-null   int64
 7   HourlyRate                         1470 non-null   int64
 8   JobInvolvement                     1470 non-null   int64
 9   JobLevel                           1470 non-null   int64
 10  JobSatisfaction                    1470 non-null   int64
 11  MonthlyIncome                      1470 non-null   int64
 12  MonthlyRate                        1470 non-null   int64
 13  NumCompaniesWorked                 1470 non-null   int64
 14  PercentSalaryHike                  1470 non-null   int64
 15  PerformanceRating                  1470 non-null   int64
 16  RelationshipSatisfaction           1470 non-null   int64
 17  StandardHours                      1470 non-null   int64
 18  StockOptionLevel                   1470 non-null   int64
 19  TotalWorkingYears                  1470 non-null   int64
 20  TrainingTimesLastYear              1470 non-null   int64
 21  WorkLifeBalance                    1470 non-null   int64
 22  YearsAtCompany                     1470 non-null   int64
 23  YearsInCurrentRole                 1470 non-null   int64
 24  YearsSinceLastPromotion            1470 non-null   int64
 25  YearsWithCurrManager               1470 non-null   int64
 26  BusinessTravel_Travel_Frequently   1470 non-null   int64
 27  BusinessTravel_Travel_Rarely       1470 non-null   int64
 28  Department_Research & Development  1470 non-null   int64
 29  Department_Sales                   1470 non-null   int64
 30  EducationField_Life Sciences       1470 non-null   int64
 31  EducationField_Marketing           1470 non-null   int64
 32  EducationField_Medical             1470 non-null   int64
 33  EducationField_Other               1470 non-null   int64
 34  EducationField_Technical Degree    1470 non-null   int64
 35  Gender_Male                        1470 non-null   int64
 36  JobRole_Human Resources            1470 non-null   int64
 37  JobRole_Laboratory Technician      1470 non-null   int64
 38  JobRole_Manager                    1470 non-null   int64
 39  JobRole_Manufacturing Director     1470 non-null   int64
 40  JobRole_Research Director          1470 non-null   int64
 41  JobRole_Research Scientist         1470 non-null   int64
 42  JobRole_Sales Executive            1470 non-null   int64
 43  JobRole_Sales Representative       1470 non-null   int64
 44  MaritalStatus_Married              1470 non-null   int64
 45  MaritalStatus_Single               1470 non-null   int64
 46  OverTime_Yes                       1470 non-null   int64
dtypes: int64(47)
memory usage: 539.9 KB

In [33]:
lb = LabelEncoder()
Y_encoded = lb.fit_transform(Y)
Y_encoded

array([1, 0, 1, ..., 0, 0, 0], shape=(1470,))

In [34]:
X_Train, X_test, y_train, y_test = train_test_split(X_encoded, Y_encoded, test_size=0.2, random_state=42)

In [35]:
X_Train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,1,0,0,0,0,0,0,0,0,0
727,18,287,5,2,1,1012,2,73,3,1,...,0,0,0,0,1,0,0,0,1,0
254,29,1247,20,2,1,349,4,45,3,2,...,0,0,0,0,0,1,0,0,0,0
1175,39,492,12,3,1,1654,4,66,3,2,...,0,0,1,0,0,0,0,1,0,0
1341,31,311,20,3,1,1881,2,89,3,2,...,1,0,0,0,0,0,0,0,0,0

In [36]:
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_Train)
X_test_scaled = sc.transform(X_test)

In [37]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout

In [38]:
model = Sequential([
    Dense(units=128, activation='relu', input_shape=(X_train_scaled.shape[1],)),     ## Input Layer
    Dropout(0.3),
    Dense(units=64, activation='relu'),                                        ## Hidden Layer
    Dropout(0.3),
    Dense(units=1, activation='sigmoid')                                       ## Output layer
])

c:\Users\singh\OneDrive\Desktop\ANN on Attrition\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 128)            │         6,144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 14,465 (56.50 KB)

 Trainable params: 14,465 (56.50 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
loss_fn = tf.keras.losses.BinaryCrossentropy()
opt = tf.keras.optimizers.SGD(learning_rate=0.001, momentum=0.9, nesterov=True)

In [41]:
model.compile(optimizer=opt, loss=loss_fn, metrics=['accuracy'])

In [42]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [43]:
## Training the Model
model.fit(
    X_train_scaled, y_train, validation_data=(X_test_scaled, y_test), epochs=50, batch_size = 8, validation_split=0.1,)

Epoch 1/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.7653 - loss: 0.5329 - val_accuracy: 0.8673 - val_loss: 0.3923
Epoch 2/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8308 - loss: 0.4560 - val_accuracy: 0.8673 - val_loss: 0.3746
Epoch 3/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8350 - loss: 0.4232 - val_accuracy: 0.8673 - val_loss: 0.3630
Epoch 4/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8384 - loss: 0.4181 - val_accuracy: 0.8673 - val_loss: 0.3533
Epoch 5/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8393 - loss: 0.3983 - val_accuracy: 0.8673 - val_loss: 0.3476
Epoch 6/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8427 - loss: 0.3857 - val_accuracy: 0.8776 - val_loss: 0.3459
Epoch 7/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8512 - loss: 0.3818 - val_accuracy: 0.8741 - val_loss: 0.3342
Epoch 8/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8554 - loss: 0.3645 - val_accuracy: 0.8776 - val_loss: 0.3300
Epoch 9/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8665 - loss: 0.3569 - val_accuracy: 0.8810 - val_loss: 0.3278
Epoch 10/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8580 - loss: 0.3493 - val_accuracy: 0.8844 - val_loss: 0.3231
Epoch 11/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8605 - loss: 0.3300 - val_accuracy: 0.9048 - val_loss: 0.3218
Epoch 12/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8699 - loss: 0.3290 - val_accuracy: 0.8980 - val_loss: 0.3193
Epoch 13/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8716 - loss: 0.3301 - val_accuracy: 0.9082 - val_loss: 0.3218
Epoch 14/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8716 - loss: 0.3310 - val_accuracy: 0.8980 - val_loss: 0.3175
Epoch 15/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8741 - loss: 0.3197 - val_accuracy: 0.8980 - val_loss: 0.3151
Epoch 16/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8793 - loss: 0.3105 - val_accuracy: 0.8946 - val_loss: 0.3154
Epoch 17/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8682 - loss: 0.3073 - val_accuracy: 0.8980 - val_loss: 0.3158
Epoch 18/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8750 - loss: 0.3044 - val_accuracy: 0.8980 - val_loss: 0.3152
Epoch 19/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8861 - loss: 0.2860 - val_accuracy: 0.9014 - val_loss: 0.3167
Epoch 20/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8759 - loss: 0.2983 - val_accuracy: 0.9014 - val_loss: 0.3185
Epoch 21/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8844 - loss: 0.2851 - val_accuracy: 0.9014 - val_loss: 0.3197
Epoch 22/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8835 - loss: 0.2924 - val_accuracy: 0.8980 - val_loss: 0.3167
Epoch 23/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8903 - loss: 0.2841 - val_accuracy: 0.8980 - val_loss: 0.3163
Epoch 24/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8801 - loss: 0.2928 - val_accuracy: 0.8946 - val_loss: 0.3191
Epoch 25/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8963 - loss: 0.2737 - val_accuracy: 0.9014 - val_loss: 0.3182
Epoch 26/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8886 - loss: 0.2681 - val_accuracy: 0.8980 - val_loss: 0.3177
Epoch 27/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8920 - loss: 0.2772 - val_accuracy: 0.8946 - val_loss: 0.3164
Epoch 28/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8954 - loss: 0.2713 - val_accuracy: 0.8946 - val_loss: 0.3157
Epoch 29/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8903 - loss: 0.2639 - val_accuracy: 0.9014 - val_loss: 0.3177
Epoch 30/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8886 - loss: 0.2602 - val_accuracy: 0.9014 - val_loss: 0.3191
Epoch 31/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8929 - loss: 0.2591 - val_accuracy: 0.8980 - val_loss: 0.3170
Epoch 32/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8971 - loss: 0.2541 - val_accuracy: 0.8946 - val_loss: 0.3180
Epoch 33/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8912 - loss: 0.2515 - val_accuracy: 0.8980 - val_loss: 0.3189
Epoch 34/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8988 - loss: 0.2543 - val_accuracy: 0.8980 - val_loss: 0.3220
Epoch 35/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9048 - loss: 0.2518 - val_accuracy: 0.8946 - val_loss: 0.3235
Epoch 36/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8878 - loss: 0.2598 - val_accuracy: 0.8946 - val_loss: 0.3268
Epoch 37/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9022 - loss: 0.2458 - val_accuracy: 0.8946 - val_loss: 0.3263
Epoch 38/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9167 - loss: 0.2293 - val_accuracy: 0.8912 - val_loss: 0.3300
Epoch 39/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9099 - loss: 0.2383 - val_accuracy: 0.8912 - val_loss: 0.3278
Epoch 40/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8997 - loss: 0.2497 - val_accuracy: 0.8844 - val_loss: 0.3276
Epoch 41/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8988 - loss: 0.2423 - val_accuracy: 0.8844 - val_loss: 0.3272
Epoch 42/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8997 - loss: 0.2376 - val_accuracy: 0.8844 - val_loss: 0.3328
Epoch 43/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8980 - loss: 0.2320 - val_accuracy: 0.8878 - val_loss: 0.3314
Epoch 44/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8997 - loss: 0.2387 - val_accuracy: 0.8878 - val_loss: 0.3322
Epoch 45/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9107 - loss: 0.2088 - val_accuracy: 0.8878 - val_loss: 0.3375
Epoch 46/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9099 - loss: 0.2167 - val_accuracy: 0.8912 - val_loss: 0.3386
Epoch 47/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9141 - loss: 0.2122 - val_accuracy: 0.8844 - val_loss: 0.3412
Epoch 48/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9090 - loss: 0.2194 - val_accuracy: 0.8878 - val_loss: 0.3427
Epoch 49/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9116 - loss: 0.2219 - val_accuracy: 0.8844 - val_loss: 0.3408
Epoch 50/50
147/147 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9158 - loss: 0.2097 - val_accuracy: 0.8878 - val_loss: 0.3420

In [44]:
loss, accuracy = model.evaluate(X_test_scaled, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8878 - loss: 0.3420

In [45]:
print(f"Test Loss : {loss:.4f} Test Accuracy = {accuracy:.4f}")

Test Loss : 0.3420 Test Accuracy = 0.8878